services:
  postgres-source:
    image: postgres:16
    container_name: postgres-source
    restart: unless-stopped
    environment:
      POSTGRES_USER: retail
      POSTGRES_PASSWORD: retail
      POSTGRES_DB: retail_oltp
    ports:
      - "5432:5432"
    volumes:
      - postgres_source_data:/var/lib/postgresql/data
    command: >
      postgres
        -c wal_level=logical
        -c max_replication_slots=4
        -c max_wal_senders=4

volumes:
  postgres_source_data:
